#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * [Portfolio Note] 
 * This utility acts as a bridge between the stored key and cryptsetup.
 * It ensures the key is passed securely via stdout to avoid leaving 
 * traces in the process list (ps).
 */

int main() {
    FILE *fp;
    char key[128];

    // 1. Open the key file generated by keygen
    // In production, this might involve re-generating the key in memory
    // to avoid storing it on disk.
    fp = fopen("key.txt", "r");
    if (fp == NULL) {
        fprintf(stderr, "❌ Error: Could not find security key.\n");
        return 1;
    }

    // 2. Read the key string
    if (fgets(key, sizeof(key), fp) != NULL) {
        // Remove potential newline characters (\n or \r)
        key[strcspn(key, "\r\n")] = 0;

        // 3. Output the key string to stdout
        // This will be piped: ./unlocker | sudo cryptsetup luksOpen ...
        printf("%s", key);
    } else {
        fprintf(stderr, "❌ Error: Security key is empty.\n");
        fclose(fp);
        return 1;
    }

    fclose(fp);
    return 0;
}
